### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by zchen6** [gavinfarnan/Project#6]
1. Maybe you can include more instructions and videos on how to use the products, so customers can have a better understanding.
2. Maybe you can also include the principles of your website.

**Comment by zchen6** [comment]
https://github.com/gavinfarnan/Project/blob/0bf265ef2eded1c4b027754384023a87f31cedba/chestfly.html#L117-121
add a hometab maybe?

**Comment by zchen6** [comment]
https://github.com/gavinfarnan/Project/blob/0bf265ef2eded1c4b027754384023a87f31cedba/propackage.html#L22-28
It would be better if you can make the logo transparent background and white.

**Comment by gavinfarnan** [comment]
I have added more information and made a homepage link. Thanks for the input!
